In [1]:
import pandas as pd
import numpy as np
import pyodbc
import sys
import os
from src.utils import read_query_file

project_path = r"C:\Users\Administrator\BDI-predator"

# add path to sys.path if not already added
if project_path not in sys.path:
    sys.path.append(project_path)

pd.set_option("display.max_columns", None)

# Data Ingestion

In [2]:
conn = pyodbc.connect(
    "DRIVER={SQL Server};SERVER=10.197.51.166;DATABASE=DataExtractionDB;UID=Predator_ML;PWD=predatorml"
)

In [11]:
sampling_pct = 0.5 / 100

In [12]:
# query_og = read_query_file("sql/join_data/02_debit_card_data.sql")
query_new = read_query_file("sql/join_data/02b_debit.sql")
query_new = query_new.format(sampling_pct=sampling_pct)

In [13]:
# df_debit = pd.read_sql(query_og, conn)
df_debit_new = pd.read_sql(query_new, conn)

C:\Users\Administrator\AppData\Local\Temp\3\ipykernel_6364\1124772204.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_debit_new = pd.read_sql(query_new, conn)

In [14]:
df_debit_new.to_parquet("data/base/df_debit_all_clean_sample_v1.parquet")

In [15]:
df_debit_new.Debit_No.nunique()

24754

In [16]:
df_debit_new

,Debit_No,Transaction Serial No,Transaction Datetime,Transaction Amount,MCC,Country Code,Card Acceptor Terminal ID,Card Acceptor Name,Card Acceptor City,Card Acceptor Region,Card Acceptor Country Code,Currency Code,CustomerAge,AccountStatus,CustomerAvgIncome,CardStatus,Balance,AgeOfOpenAcctTxn,AgeOfActiveCardTxn,AgeOfOpenAcctActiveCard,TrfToBDIStaff,BDIStaff,AgeOfRegDateTxn,IsSDBPastDue,FlagOutBranch,isTDHoldAmount,isProgramHoldAmount,IsOfficeHour,VALAS,ChannelTrx,LastTrxAmount,DrLastTrxAmount,CrLastTrxAmount,TotalTrxAmountL1D,DrTotalTrxAmountL1D,CrTotalTrxAmountL1D,TotalTrxAmountL7D,DrTotalTrxAmountL7D,CrTotalTrxAmountL7D,TotalTrxAmountL1M,DrTotalTrxAmountL1M,CrTotalTrxAmountL1M,AvgTrxAmountL1D,AvgTrxAmountL7D,AvgTrxAmountL1M,TotalTrxAmount15Mi,HIghRiskCustomer,ProductName,PrevAccStatus,HoldAmountTB,HoldAmountDP,SDBBalance,CCBrnAccount,CCBrnReactivedAccDormant,BrnNameReactivedAccDormant,TrxBranchName,IsWhiteList,IsBlacklistAccount,IsBlacklistCust,ProductCodeTo,AccessCode,SDBBoxNo,SDBStatus,SDBLastPaymentAmount,FlagTxnDesc,ProductCodeDep,IsMerchantBDI,NumOfTrxL1D,NumOfTrxL7D,IsHighRiskCountry,IsBlacklistMerchant,IsWatchListMerchant,IsHighRiskMCC,CreditLimit,CashCreditLimit,CardProduct,CustomerSex,IsBlacklistCardNo,IsValidCard,Currency,POSMode,PINEntryCapability,IsCardExpired,Is3DSecure,IsWhiteListMerchant,IsBDIEmail,IsWhiteListCardNo,IsWhiteListAccountNo,IsWatchListAccountNo,IsAccountBDIEmployee,CodAccess,TransactionType,TotalTrxAmount10Mi,CustomerType,TotalTrxAmountL5min,TotalTrxAmountContactless,IsWhitelistCardNoOpen,DaysOfWhitelistCardNoOpen,IsVAAccount,IsExcludeTeminalId,isBDICard,IsWatchlistCardNo,SourceChannel,IsBlackListTID,IsFirstTrx3DS,VCardDataInputCapability,CustomerNationality,TotalTrxAmountContactlessPerDay,IsTopUp,IsBillPayment,IsPaymentToVA,TotalTrxAmountTopUp1,TotalTrxAmountTopUp2,TotalTrxAmountVA1,TotalTrxAmountVA2,CustomerEwaletNumber,IsHighRiskCountryThresholdAmt,IsHighRiskCurrency,IsHighRiskCurrencyThresholdAmt,IsQRtrx,IsDCashTrx,IsFTTrx,TotalTrxAmountQRIS,TotalTrxAmountDcash,TotalTrxAmountTrf,CountTrxQRIS,CountTrxTrf,TotalTrxAmountTrf2,CountTrxQRIS2,CountTrxDcash,CountTrxTrf2,NumOfTrxL15Min,IsWhitelistCardNoPrevilage,IsWhiteListTID,IsWatchListTID,TimeDiffCurrPrev,TotalTrxAmount30Mi,IsBucket1WatchListCardNo,IsBucket1BlacklistCardNo,IsBucket1WhiteListCardNo,IsBucket2WhiteListMerchant,IsBucket2WatchListMerchant,IsBucket2BlacklistMerchant,CountTrxEOD,Confirmed
0,"b',w\x82U\x94\x17\x1e\xa6mk\x8f\xe1\xc6\xb9\xf...",967448932,2024-08-31 00:21:43,4325000.0,6014,IDN,99102000,MANDIRI CASH MANAGEMEN,MANDIRI CASH,021,IDN,360,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4625000.0,None,None,None,None,None,None,None,None,None,None,None,4325000.0,None,None,None,None,None,None,None,None,None,None,None,N,None,None,None,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,None,None,None,None,None,2,S,None,None,N,N,N,N,N,None,None,23,4325000.0,None,4325000.0,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,N,N,N,NaN,NaN,NaN,NaN,"b""\xb9\x07f\x17\xe8'\x1b\xcd\x9b\xe7?\xa2BD\x9...",None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None
1,b'\xbb\xc5\x11\xbcl\x15]\x1a\xd1\x12r\xb1h\xf9...,967770884,2024-08-31 00:23:26,19500.0,6017,IDN,POS00008,Gopay-Gojek,DKI Jakarta,000,IDN,360,24.0,8,None,2,170000.00,NaN,NaN,None,None,N,None,None,None,None,None,None,None,None,None,None,None,52500.0,None,None,None,None,None,None,None,None,None,None,None,19500.0,N,None,None,None,None,None,891,None,None,None,None,N,None,None,1000,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,30,F,None,None,None,1,1,None,None,N,N,N,N,N,None,None,00,19500.0,None,19500.0,NaN,None,None,None,None,None,None,None,None,None,None,ID,NaN,Y,N,N,NaN,NaN,NaN,NaN,"b""\xe3\xb0\xc4B\x98\xfc\x1c\x14\x9a\xfb\xf4\xc...",None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None
2,b'0w\xe4Ro\xca+\xa1\xa4Y\xf8\x98\x8a\x0f\xdf\x...,967449687,2024-08-31 00:32:21,150000.0,6011,IDN,00001405,BDI SUDIRMAN,PURWOKERTO,000,IDN,360,31.0,8,None,2,1871304.82,4687.0,550.0,None,None,N,None,None,None,None,None,None,None,None,None,None,None,150000.0,None,None,None,None,None,None,None,None,None,None,None,150000.0,N,None,None,None,None,None,702,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1.0,None,N,N,N,None,None,None,71,M,N,None,IDR,5,0,None,None,N,N,None,None,None,None,None,40,150000.0,None,150000.0,NaN,None,None,N,N,Y,None,None,None,None,5,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,1.0,None,None,None,None,None,None,None,0.0,None
3,b'0w\xe4Ro\xca+\xa1\xa4Y\xf8\x98\x8a\x0f\xdf\x...,967449785,2024-08-31 00:33:29,1900000.0,6011,IDN,80000149,JL. JEND. SUDIRMAN,PURWOKERTO,,IDN,360,31.0,8,None,2,1871304.82,4687.0,550.0,None,None,N,None,None,None,None,None,None,None,None,None,None,None,2050000.0,None,None,None,None,None,None,None,None,None,None,None,2050000.0,N,None,None,None,None,None,702,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2.0,None,N,N,N,None,None,None,71,M,N,None,IDR,5,0,None,None,N,N,None,None,None,None,None,01,2050000.0,None,2050000.0,NaN,None,None,N,N,Y,None,None,None,None,5,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,1.0,None,None,None,None,None,None,None,0.0,None
4,b'0w\xe4Ro\xca+\xa1\xa4Y\xf8\x98\x8a\x0f\xdf\x...,967449853,2024-08-31 00:34:19,50000.0,6011,IDN,80000149,JL. JEND. SUDIRMAN,PURWOKERTO,,IDN,360,31.0,8,None,2,1871304.82,4687.0,550.0,None,None,N,None,None,None,None,None,None,None,None,None,None,None,2100000.0,None,None,None,None,None,None,None,None,None,None,None,2100000.0,N,None,None,None,None,None,702,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3.0,None,N,N,N,None,None,None,71,M,N,None,IDR,5,0,None,None,N,N,None,None,None,None,None,01,2100000.0,None,2100000.0,NaN,None,None,N,N,Y,None,None,None,None,5,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,1.0,None,None,None,None,None,None,None,0.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334630,"b'\xf2)[&ds\x82\xd4\xf8""N\x15\x00W4I\xc6\x84\x...",1143905448,2025-05-26 22:33:35,0.0,None,None,None,None,None,None,None,360,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,N,None,None,None,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,None,None,None,None,None,None,None,None,None,N,N,N,N,N,None,None,BI,0.0,None,0.0,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,N,N,N,NaN,NaN,NaN,NaN,"b'\xc0""\x03aV\xc7]RF2\x03\x1d\xa0\xfe\x91\xedZ...",None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None
334631,"b'\x8f\xeeaI\x9c\x91""\xdc\xd1l\xede\x8fq5\x18&...",1143905596,2025-05-26 22:34:34,0.0,None,None,None,None,None,None,None,360,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,N,None,None,None,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,None,None,None,None,None,None,None,None,None,N,N,N,N,N,None,None,BI,0.0,None,0.0,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,N,N,N,NaN,NaN,NaN,NaN,b'\xcd6\x10\x03\x14_s\xc3DN\x18\xf7\xeb\xa5|\x...,None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None
334632,b'\xda\x96\x9fT>@\xe3]\xa1\x9aE\x81!4\xa1<\xfa...,1143913275,2025-05-26 23:33:16,NaN,6011,IDN,80000836,JL. HM. RAFII MADURE,PANGKALAN BUN,,IDN,360,32.0,8,None,2,4669.15,2687.0,801.0,None,None,N,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,N,None,None,None,None,None,521,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,N,N,N,None,None,None,51,M,N,None,IDR,5,0,None,None,N,N,None,None,None,None,None,31,NaN,None,NaN,NaN,None,None,N,N,Y,None,None,None,None,5,None,NaN,None,None,None,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,4590.0,None,None,None,None,None,None,None,0.0,None
334633,b'n\xf2\xa9\xc5V\x15A\xcaU\xf5\xa7v\xa7\xd7a\x...,1143898855,2025-05-26 21:54:20,NaN,None,None,None,None,None,None,None,360,35.0,8,None,2,1492467.46,NaN,NaN,None,None,N,None,None,None,None,None,None,None,None,None,None,None,1281292.0,None,None,None,None,None,None,None,None,None,None,None,NaN,N,None,None,None,None,None,373,None,None,None,None,N,None,None,None,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,30,M,None,None,None,None,None,None,None,N,N,N,N,N,None,None,in,NaN,None,NaN,NaN,None,None,None,None,None,None,None,None,None,None,ID,NaN,N,N,N,NaN,NaN,NaN,1281292.0,b'V\x18\xadPF\x08)>\xe8TP\x82\xc04\x08[\xce\xc...,None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None
334634,"b""8!\xfc\xcfx\xc1'\x88\xa9rb\t\x7f\xac\xc5f7\x...",1143914002,2025-05-26 23:39:09,0.0,None,None,None,None,None,None,None,360,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,N,None,None,None,None,None,None,None,None,None,0.0,None,None,None,N,None,None,None,None,None,None,None,None,None,None,None,None,N,N,N,N,N,None,None,BI,0.0,None,0.0,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,N,N,N,NaN,NaN,NaN,NaN,b'\\\xe5\xce\xb0\x12\xe4\x1f\xcd\x15\xe9\x02s\...,None,None,None,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,None,None,NaN,None,None,None,None,None,None,None,NaN,None

In [5]:
df_debit.to_parquet("data/base/df_debit_sample_v4.parquet")

In [7]:
df_debit["Transaction Datetime"] = pd.to_datetime(df_debit["Transaction Datetime"])

In [8]:
df_debit[
    df_debit["Debit_No"]
    == b"\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):\xc2\x0c\x86\xdf:\xa1W/\xa1\x9fn\x1fmI"
][
    [
        "Debit_No",
        "Transaction Serial No",
        "Transaction Datetime",
        "Transaction Amount",
        "Confirmed",
    ]
].sort_values(
    "Transaction Datetime", ascending=True
)

,Debit_No,Transaction Serial No,Transaction Datetime,Transaction Amount,Confirmed
213733,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1070784510,2025-01-21 19:03:10,91200.0,NaN
256601,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1087329018,2025-02-20 18:07:25,171050.0,NaN
256667,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1087348103,2025-02-20 19:14:43,38500.0,NaN
260162,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1088640674,2025-02-23 12:27:27,100000.0,NaN
262050,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1089843360,2025-02-24 19:29:02,15000.0,NaN
262011,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1089844992,2025-02-24 19:34:44,21500.0,NaN
322048,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1119102497,2025-04-13 16:14:48,600000.0,NaN
325402,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1120530940,2025-04-16 09:29:07,27820265.0,NaN
333477,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1123644542,2025-04-22 13:24:35,4000000.0,NaN
336234,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1124787441,2025-04-24 14:02:12,118999.0,NaN
338006,b'\r\x9e\xf3%\xc5\x1d\n5}\xe5\xd9\x0c\x0cRE5):...,1125579402,2025-04-25 18:45:18,17500000.0,1.0