In [1]:
import pandas as pd
import numpy as np

In [2]:
from src.credit_card_config import (
    freq_config_pos_mode,
    monetary_config_pos_mode,
    first_time_trnx_duration_config,
    time_windows,
)
from src.calculation_features import generate_rolling_features

In [3]:
df_mock = pd.read_csv("data/mock/mock_data_join_c03_tscf.csv")
df_mock = df_mock.drop(["Unnamed: 0"], axis=1)

/tmp/ipykernel_158761/648126267.py:1: DtypeWarning: Columns (13,28,33,53,112,120,128,139,144,160,177,178,179,182,183,184,185,186,187) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mock = pd.read_csv("data/mock/mock_data_join_c03_tscf.csv")

In [4]:
df_mock["Transaction Datetime"] = pd.to_datetime(df_mock["Transaction Datetime"])
df_mock["POS Entry Mode"] = df_mock["POS Entry Mode"].astype(str)

# Frequency

In [5]:
df_mock_freq = generate_rolling_features(
    df_mock,
    datetime_col="Transaction Datetime",
    key_col="Transaction Serial No",
    features_config=freq_config_pos_mode,
)

Feature Config Progress:   0%|          | 0/1 [00:00<?, ?it/s]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:297: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:297: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress: 100%|██████████| 1/1 [00:02<00:00,  2.67s/it]

In [6]:
df_mock_freq

,PANNumber,Transaction Serial No,Transaction Datetime,Product Indicator,Transaction Amount,Card Billing Amount,MCC,Country Code,POS Entry Mode,POS Condition Code,...,IsBucket3BlacklistMID,IsFacebookBlacklistMerchant,Confirmed,TxnCount_to_POSMode_L15M,TxnCount_to_POSMode_L1H,TxnCount_to_POSMode_L1D,TxnCount_to_POSMode_L7D,TxnCount_to_POSMode_L14D,TxnCount_to_POSMode_L30D,TxnCount_to_POSMode_L90D
0,798887404,916615399,2024-06-25 03:01:01,2,0.00,NaN,5969.0,360,10.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,798887404,916615420,2024-06-25 03:01:06,2,14000.00,14000.00,5816.0,360,12.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,798887404,916615503,2024-06-25 03:01:06,2,14000.00,14000.00,NaN,360,12.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,681381357,915272480,2024-06-23 10:00:49,2,2052000.00,2052000.00,7399.0,360,12.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,998206419,916488908,2024-06-25 10:23:53,2,1552170.00,1552170.00,5999.0,360,10.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35398,767562423,913891894,2024-06-21 11:56:00,2,271259.18,16.51,5311.0,840,10.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35399,175699529,912484146,2024-06-19 07:38:20,2,5350949.60,325.88,5818.0,840,12.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35400,698042094,913764542,2024-06-21 07:32:35,2,0.00,NaN,5969.0,360,10.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35401,688228199,911896756,2024-06-18 10:48:37,2,0.00,NaN,5969.0,360,10.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35402,547883901,911877928,2024-06-18 06:59:57,2,6876815.00,6876815.00,NaN,360,12.0,15.0,...,NaN,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df_mock_freq[df_mock_freq["PANNumber"] == 798887404][
    [
        "PANNumber",
        "Transaction Serial No",
        "POS Entry Mode",
        "Transaction Datetime",
        "TxnCount_to_POSMode_L15M",
        "TxnCount_to_POSMode_L1H",
        "TxnCount_to_POSMode_L1D",
        "TxnCount_to_POSMode_L7D",
        "TxnCount_to_POSMode_L14D",
        "TxnCount_to_POSMode_L30D",
        "TxnCount_to_POSMode_L90D",
    ]
].sort_values(by="Transaction Datetime")

,PANNumber,Transaction Serial No,POS Entry Mode,Transaction Datetime,TxnCount_to_POSMode_L15M,TxnCount_to_POSMode_L1H,TxnCount_to_POSMode_L1D,TxnCount_to_POSMode_L7D,TxnCount_to_POSMode_L14D,TxnCount_to_POSMode_L30D,TxnCount_to_POSMode_L90D
0,798887404,916615399,10.0,2024-06-25 03:01:01,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,798887404,916615420,12.0,2024-06-25 03:01:06,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,798887404,916615503,12.0,2024-06-25 03:01:06,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,798887404,916615963,10.0,2024-06-25 03:03:04,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Monetary

In [8]:
df_mock_monetary = generate_rolling_features(
    df_mock,
    datetime_col="Transaction Datetime",
    key_col="Transaction Serial No",
    features_config=monetary_config_pos_mode,
)

Feature Config Progress:   0%|          | 0/3 [00:00<?, ?it/s]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress:  33%|███▎      | 1/3 [00:02<00:05,  2.56s/it]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress:  67%|██████▋   | 2/3 [00:05<00:02,  2.59s/it]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:365: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress: 100%|██████████| 3/3 [00:08<00:00,  2.67s/it]

In [9]:
selected_cols = [col for col in df_mock_monetary.columns if "_Amt_" in col]

In [10]:
df_mock_monetary.head(50)

,PANNumber,Transaction Serial No,Transaction Datetime,Product Indicator,Transaction Amount,Card Billing Amount,MCC,Country Code,POS Entry Mode,POS Condition Code,...,Max_Amt_to_POSMode_L14D,Max_Amt_to_POSMode_L30D,Max_Amt_to_POSMode_L90D,Sum_Amt_to_POSMode_L15M,Sum_Amt_to_POSMode_L1H,Sum_Amt_to_POSMode_L1D,Sum_Amt_to_POSMode_L7D,Sum_Amt_to_POSMode_L14D,Sum_Amt_to_POSMode_L30D,Sum_Amt_to_POSMode_L90D
0,798887404,916615399,2024-06-25 03:01:01,2,0.00,NaN,5969.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,798887404,916615420,2024-06-25 03:01:06,2,14000.00,14000.00,5816.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,798887404,916615503,2024-06-25 03:01:06,2,14000.00,14000.00,NaN,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,681381357,915272480,2024-06-23 10:00:49,2,2052000.00,2052000.00,7399.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,998206419,916488908,2024-06-25 10:23:53,2,1552170.00,1552170.00,5999.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,713190161,916357110,2024-06-25 03:00:55,2,23516526.00,23516526.00,4722.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,713190161,916357118,2024-06-25 03:00:57,2,0.00,NaN,5969.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,513858853,916464025,2024-06-25 04:41:02,2,29000.00,29000.00,5818.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,291173012,916356681,2024-06-25 09:59:45,2,2776133.00,2776133.00,7311.0,360,10.0,15.0,...,2776133.0,2776133.0,2776133.0,5572266.0,5572266.0,5572266.0,5572266.0,5572266.0,5572266.0,5572266.0
9,492525802,916535667,2024-06-25 11:40:20,2,207.56,0.02,5964.0,392,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,492525802,916535689,2024-06-25 11:40:20,2,207.56,0.02,NaN,392,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,630616678,916405287,2024-06-25 03:02:47,2,996000.00,996000.00,5499.0,360,10.0,15.0,...,25001000.0,25001000.0,25001000.0,55200999.0,55200999.0,55200999.0,55200999.0,55200999.0,55200999.0,55200999.0
12,530267619,915345201,2024-06-23 06:23:23,2,0.00,NaN,5941.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,271191714,914487854,2024-06-22 01:43:19,2,10000.00,10000.00,5818.0,360,12.0,15.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
14,271191714,914488108,2024-06-22 01:43:19,2,10000.00,10000.00,NaN,360,12.0,15.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
15,967873970,916464441,2024-06-25 04:41:47,2,31999.00,31999.00,5816.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,798887404,916615963,2024-06-25 03:03:04,2,0.00,NaN,5968.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,730679829,916611866,2024-06-25 09:46:27,2,173160.00,173160.00,4722.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,987883457,914244221,2024-06-22 01:54:47,2,25680610.00,25680610.00,5965.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,711210266,914244524,2024-06-22 01:56:22,2,57142.00,57142.00,5818.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,630616678,916403827,2024-06-25 02:59:56,2,10149999.00,10149999.00,5999.0,360,10.0,15.0,...,25001000.0,25001000.0,25001000.0,45051000.0,45051000.0,45051000.0,45051000.0,45051000.0,45051000.0,45051000.0
21,271191714,914487624,2024-06-22 01:40:41,2,10000.00,10000.00,NaN,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,419723730,916535702,2024-06-25 11:40:25,2,45000.00,45000.00,5818.0,360,10.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,453024456,914545247,2024-06-22 10:30:08,2,11000.00,11000.00,4899.0,360,12.0,15.0,...,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0
24,430579308,916358941,2024-06-25 03:05:56,2,8535200.00,8535200.00,5999.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,178249263,914606556,2024-06-22 10:28:50,2,0.00,NaN,8999.0,360,10.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,730679829,916611911,2024-06-25 09:46:39,2,173160.00,173160.00,7011.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,453024456,914545262,2024-06-22 10:30:12,2,1300000.00,1300000.00,4899.0,360,12.0,15.0,...,11000.0,11000.0,11000.0,33000.0,33000.0,33000.0,33000.0,33000.0,33000.0,33000.0
28,271191714,914489061,2024-06-22 01:47:56,2,10000.00,10000.00,5818.0,360,12.0,15.0,...,10000.0,10000.0,10000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0
29,453024456,914546252,2024-06-22 10:29:12,2,11000.00,11000.00,NaN,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,291173012,916356799,2024-06-25 10:00:04,2,2776133.00,2776133.00,7311.0,360,10.0,15.0,...,2776133.0,2776133.0,2776133.0,8348399.0,8348399.0,8348399.0,8348399.0,8348399.0,8348399.0,8348399.0
31,897974888,916543974,2024-06-25 06:56:21,2,11783653.36,9900.00,5969.0,410,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,627877498,915273183,2024-06-23 10:03:58,2,0.00,NaN,7011.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,627877498,915273192,2024-06-23 10:03:59,2,0.00,NaN,7011.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,271191714,914489419,2024-06-22 01:49:29,2,10000.00,10000.00,7399.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,472225477,915540355,2024-06-24 12:12:35,2,0.00,NaN,5331.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,291173012,916356812,2024-06-25 10:00:05,2,2776133.00,2776133.00,7311.0,360,10.0,8.0,...,2776133.0,2776133.0,2776133.0,11124532.0,11124532.0,11124532.0,11124532.0,11124532.0,11124532.0,11124532.0
37,291173012,916356819,2024-06-25 10:00:06,2,2776133.00,2776133.00,7311.0,360,10.0,15.0,...,2776133.0,2776133.0,2776133.0,13900665.0,13900665.0,13900665.0,13900665.0,13900665.0,13900665.0,13900665.0
38,514861475,914606783,2024-06-22 10:30:49,2,3909856.00,3909856.00,5999.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,416567446,916399599,2024-06-25 07:51:45,2,4740900.00,4740900.00,5999.0,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,164474904,916570451,2024-06-25 07:51:50,2,5528571.00,5528571.00,5817.0,360,12.0,15.0,...,18428570.0,18428570.0,18428570.0,36857140.0,36857140.0,36857140.0,36857140.0,36857140.0,36857140.0,36857140.0
41,399951998,914508099,2024-06-22 02:11:34,2,15000.00,15000.00,NaN,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,987883457,914417870,2024-06-22 02:11:43,2,8579791.00,8579791.00,5965.0,360,10.0,15.0,...,25680610.0,25680610.0,25680610.0,4367650.0,30048260.0,30048260.0,30048260.0,30048260.0,30048260.0,30048260.0
43,896529641,916428449,2024-06-25 08:41:41,2,0.00,NaN,7372.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,453024456,914546454,2024-06-22 10:30:08,2,11000.00,11000.00,NaN,360,12.0,15.0,...,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0
45,987883457,914418326,2024-06-22 02:14:07,2,2984031.00,2984031.00,5965.0,360,10.0,15.0,...,25680610.0,25680610.0,25680610.0,12947441.0,38628051.0,38628051.0,38628051.0,38628051.0,38628051.0,38628051.0
46,998028611,915925787,2024-06-24 11:19:54,2,380000.00,380000.00,NaN,360,12.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,784968984,914513196,2024-06-22 08:23:53,2,10000.00,10000.00,7399.0,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,784968984,914513200,2024-06-22 08:23:53,2,10000.00,10000.00,NaN,360,10.0,15.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,784968984,914513240,2024-06-22 08:24:06,2,12210.00,12210.00,5817.0,360,10.0,8.0,...,10000.0,10000.0,10000.0,20000.0,20000.0,20000.0,20000.0,20000.0,20000.0,20000.0

In [11]:
df_mock_monetary[df_mock_freq["PANNumber"] == 271191714][
    [
        "PANNumber",
        "Transaction Serial No",
        "Transaction Datetime",
        "POS Entry Mode",
        "Transaction Amount",
    ]
    + selected_cols
].sort_values(by="Transaction Datetime")

,PANNumber,Transaction Serial No,Transaction Datetime,POS Entry Mode,Transaction Amount,Avg_Amt_to_POSMode_L15M,Avg_Amt_to_POSMode_L1H,Avg_Amt_to_POSMode_L1D,Avg_Amt_to_POSMode_L7D,Avg_Amt_to_POSMode_L14D,...,Max_Amt_to_POSMode_L14D,Max_Amt_to_POSMode_L30D,Max_Amt_to_POSMode_L90D,Sum_Amt_to_POSMode_L15M,Sum_Amt_to_POSMode_L1H,Sum_Amt_to_POSMode_L1D,Sum_Amt_to_POSMode_L7D,Sum_Amt_to_POSMode_L14D,Sum_Amt_to_POSMode_L30D,Sum_Amt_to_POSMode_L90D
21,271191714,914487624,2024-06-22 01:40:41,12.0,10000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,271191714,914487854,2024-06-22 01:43:19,12.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
14,271191714,914488108,2024-06-22 01:43:19,12.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
28,271191714,914489061,2024-06-22 01:47:56,12.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,10000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0
34,271191714,914489419,2024-06-22 01:49:29,10.0,10000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Duration since First Time Trnx

In [12]:
df_mock.rename({"Country Code": "CountryCode"}, axis=1, inplace=True)

In [13]:
df_mock_first_time_duration = generate_rolling_features(
    df_mock,
    datetime_col="Transaction Datetime",
    key_col="Transaction Serial No",
    features_config=first_time_trnx_duration_config,
)

Feature Config Progress:   0%|          | 0/2 [00:00<?, ?it/s]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:535: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:535: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress:  50%|█████     | 1/2 [00:02<00:02,  2.99s/it]/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:535: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  .rolling(window, closed="left")
/home/gregorius_vidy/gbg_analytics/01 Experimentation/Bespoke ML Pipeline/bespoke-ml/src/calculation_features.py:535: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  .rolling(window, closed="left")
Feature Config Progress: 100%|██████████| 2/2 [00:06<00:00,  3.02s/it]

In [14]:
df_mock_first_time_duration = df_mock_first_time_duration.sort_values(
    by=["PANNumber", "Transaction Datetime"]
)
for groupby_col in ["MCC", "CountryCode"]:
    df_mock_first_time_duration[f"first_txn_time_by_{groupby_col}"] = (
        df_mock_first_time_duration.groupby(["PANNumber", groupby_col])[
            "Transaction Datetime"
        ].transform("first")
    )

    amount_col = f"DurationSince_FirstTrnx_to_Current_{groupby_col}"
    df_mock_first_time_duration[amount_col] = (
        df_mock_first_time_duration["Transaction Datetime"]
        - df_mock_first_time_duration[f"first_txn_time_by_{groupby_col}"]
    ).dt.total_seconds() / 60

    df_mock_first_time_duration.drop(
        [f"first_txn_time_by_{groupby_col}"], axis=1, inplace=True
    )

In [15]:
selected_cols = [
    col for col in df_mock_first_time_duration.columns if "DurationSince" in col
]

In [16]:
selected_cols

['Avg_DurationSince_FirstTrnx_to_Current_MCC_L15M',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L1H',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L1D',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L7D',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L14D',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L30D',
 'Avg_DurationSince_FirstTrnx_to_Current_MCC_L90D',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L15M',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L1H',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L1D',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L7D',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L14D',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L30D',
 'Avg_DurationSince_FirstTrnx_to_Current_CountryCode_L90D',
 'DurationSince_FirstTrnx_to_Current_MCC',
 'DurationSince_FirstTrnx_to_Current_CountryCode']

In [17]:
df_mock_first_time_duration[df_mock_first_time_duration["PANNumber"] == 271191714][
    [
        "PANNumber",
        "Transaction Serial No",
        "Transaction Datetime",
        "MCC",
        "CountryCode",
        "DurationSince_FirstTrnx_to_Current_MCC",
        "DurationSince_FirstTrnx_to_Current_CountryCode",
    ]
].sort_values(by="Transaction Datetime", ascending=True)

,PANNumber,Transaction Serial No,Transaction Datetime,MCC,CountryCode,DurationSince_FirstTrnx_to_Current_MCC,DurationSince_FirstTrnx_to_Current_CountryCode
21,271191714,914487624,2024-06-22 01:40:41,NaN,360,NaN,0.000000
13,271191714,914487854,2024-06-22 01:43:19,5818.0,360,0.000000,2.633333
14,271191714,914488108,2024-06-22 01:43:19,NaN,360,NaN,2.633333
28,271191714,914489061,2024-06-22 01:47:56,5818.0,360,4.616667,7.250000
34,271191714,914489419,2024-06-22 01:49:29,7399.0,360,0.000000,8.800000

In [18]:
df_test = df_mock[
    [
        "PANNumber",
        "Transaction Serial No",
        "Transaction Datetime",
        "POS Entry Mode",
        "CountryCode",
        "Transaction Amount",
    ]
].copy()

In [19]:
df_test = df_test.sort_values(by=["PANNumber", "Transaction Datetime"])

In [20]:
df_test[df_test["PANNumber"] == 271191714].groupby(["PANNumber", "POS Entry Mode"])[
    "Transaction Datetime"
].transform("first")

21   2024-06-22 01:40:41
13   2024-06-22 01:40:41
14   2024-06-22 01:40:41
28   2024-06-22 01:40:41
34   2024-06-22 01:49:29
Name: Transaction Datetime, dtype: datetime64[ns]

In [21]:
df_test[df_test["PANNumber"] == 271191714].groupby(["PANNumber", "POS Entry Mode"])[
    "Transaction Datetime"
].min()

PANNumber  POS Entry Mode
271191714  10.0             2024-06-22 01:49:29
           12.0             2024-06-22 01:40:41
Name: Transaction Datetime, dtype: datetime64[ns]

# Dynamic High Risk MCC

In [22]:
df_mock.Confirmed

0        0
1        0
2        0
3        0
4        0
        ..
35398    0
35399    0
35400    0
35401    0
35402    0
Name: Confirmed, Length: 35403, dtype: int64

In [38]:
dynamic_high_risk_mcc_config = {
    "groupby": "MCC",
    "fraud_label_col": "Confirmed",
    "agg_func": "sum",
    "months_period": 12,  # e.g. last 1 months
    "risk_label": ["very_high", "high", "medium", "low"],
    "risk_threshold": [0.9, 0.75, 0.4],
}

In [39]:
from src.calculation_features import label_risk_level_category

In [40]:
df_mock["MCC"] = df_mock["MCC"].fillna("__missing__")

In [41]:
df_mock = label_risk_level_category(
    df=df_mock, datetime_col="Transaction Datetime", config=dynamic_high_risk_mcc_config
)

In [43]:
df_mock[df_mock["PANNumber"] == 271191714][
    # df_mock[df_mock['MCCRiskLevel'].isna()][
    [
        "PANNumber",
        "Transaction Serial No",
        "Transaction Datetime",
        "MCC",
        "MCCRiskLevel",
    ]
].sort_values(by="Transaction Datetime", ascending=True)

,PANNumber,Transaction Serial No,Transaction Datetime,MCC,MCCRiskLevel
21,271191714,914487624,2024-06-22 01:40:41,__missing__,low
13,271191714,914487854,2024-06-22 01:43:19,5818.0,low
14,271191714,914488108,2024-06-22 01:43:19,__missing__,low
28,271191714,914489061,2024-06-22 01:47:56,5818.0,low
34,271191714,914489419,2024-06-22 01:49:29,7399.0,low

In [46]:
# Define the reference window
max_date = df_mock["Transaction Datetime"].max()
min_date = max_date - pd.DateOffset(months=12)

# Filter transactions in the reference window
reference_df = df_mock[
    (df_mock["Transaction Datetime"] >= min_date)
    & (df_mock["Transaction Datetime"] <= max_date)
]

# Group by MCC and normalized
agg_df = reference_df.groupby("MCC")["Confirmed"].agg("sum")

In [47]:
agg_df

MCC
742.0            0
780.0            1
1711.0           2
1731.0          19
1740.0           4
              ...
8999.0          15
9311.0          15
9399.0          11
9406.0           0
__missing__    618
Name: Confirmed, Length: 233, dtype: int64

In [36]:
df_mock["MCCRiskLevel"].unique()

array(['low', nan], dtype=object)